// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectInstallDir() {
  return window['go']['main']['App']['SelectInstallDir']();
}

export function StartUpdate(arg1) {
  return window['go']['main']['App']['StartUpdate'](arg1);
}
