// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetState():Promise<main.UpdaterSnapshot>;

export function LaunchApp(arg1:string):Promise<string>;

export function Refresh():Promise<main.UpdaterSnapshot>;

export function SaveSettings(arg1:main.SaveSettingsInput):Promise<main.UpdaterSnapshot>;

export function SelectInstallDir():Promise<string>;

export function StartUpdate(arg1:string):Promise<main.UpdaterSnapshot>;
