// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyControls(arg1) {
  return window['go']['main']['App']['ApplyControls'](arg1);
}

export function ClearRows() {
  return window['go']['main']['App']['ClearRows']();
}

export function ExportRows() {
  return window['go']['main']['App']['ExportRows']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function SetCursorIndex(arg1) {
  return window['go']['main']['App']['SetCursorIndex'](arg1);
}
