// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyControls(arg1:main.ViskoControls):Promise<main.ViskoSnapshot>;

export function ClearRows():Promise<main.ViskoSnapshot>;

export function ExportRows():Promise<main.ViskoSnapshot>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetSnapshot():Promise<main.ViskoSnapshot>;

export function SetCursorIndex(arg1:number):Promise<main.ViskoSnapshot>;
