// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateConfigs(arg1) {
  return window['go']['main']['App']['GenerateConfigs'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function SaveMasterSettings(arg1) {
  return window['go']['main']['App']['SaveMasterSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
