// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateConfigs(arg1:main.MasterSettings):Promise<main.MasterSnapshot>;

export function GetState():Promise<main.MasterSnapshot>;

export function SaveMasterSettings(arg1:main.MasterSettings):Promise<main.MasterSnapshot>;

export function SelectDirectory():Promise<string>;
