// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Calculate():Promise<main.RP40Snapshot>;

export function GetSnapshot():Promise<main.RP40Snapshot>;

export function SelectMeasurementFile():Promise<main.RP40Snapshot>;

export function SelectPassportFile():Promise<main.RP40Snapshot>;

export function SetSelectedSample(arg1:string):Promise<main.RP40Snapshot>;

export function UpdateInputs(arg1:main.RP40Inputs):Promise<main.RP40Snapshot>;
