// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate() {
  return window['go']['main']['App']['Calculate']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function SelectMeasurementFile() {
  return window['go']['main']['App']['SelectMeasurementFile']();
}

export function SelectPassportFile() {
  return window['go']['main']['App']['SelectPassportFile']();
}

export function SetSelectedSample(arg1) {
  return window['go']['main']['App']['SetSelectedSample'](arg1);
}

export function UpdateInputs(arg1) {
  return window['go']['main']['App']['UpdateInputs'](arg1);
}
